/*
 * This header is generated by weak_classdump 0.2
 * on Monday, May 12, 2014 at 9:26:46 PM Mountain Daylight Time
 * Operating System: Version 7.0.4 (Build 11B554a)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol MPDetailedScrubbing
@required
-(float)value;
-(float)minimumValue;
-(float)maximumValue;
-(float)value;
-(float)minimumValue;
-(float)maximumValue;
@end

@protocol MPDetailScrubControllerDelegate
@optional
-(void)detailScrubControllerDidBeginScrubbing:(id)arg1 ;
-(void)detailScrubControllerDidEndScrubbing:(id)arg1 ;
-(void)detailScrubController:(id)arg1 didChangeValue:(float)arg2 ;
-(void)detailScrubController:(id)arg1 didChangeScrubSpeed:(int)arg2 ;
@end
