/*
 * This header is generated by weak_classdump 0.2
 * on Tuesday, May 13, 2014 at 2:44:02 PM Mountain Daylight Time
 * Operating System: Version 7.0.4 (Build 11B554a)
 * weak_classdump is Freeware by Elias Limneos.
 *
 */


@protocol MPUNowPlayingDelegate
@optional
-(void)nowPlayingControllerDidBeginListeningForNotifications:(id)arg1 ;
-(void)nowPlayingControllerDidStopListeningForNotifications:(id)arg1 ;
-(void)nowPlayingController:(id)arg1 nowPlayingInfoDidChange:(id)arg2 ;
-(void)nowPlayingController:(id)arg1 playbackStateDidChange:(BOOL)arg2 ;
-(void)nowPlayingController:(id)arg1 nowPlayingApplicationDidChange:(id)arg2 ;
-(void)nowPlayingController:(id)arg1 elapsedTimeDidChange:(double)arg2 ;
@end

@protocol MPUTransportControlsViewDelegate
@optional
-(void)transportControlsView:(id)arg1 tapOnControlType:(int)arg2 ;
-(void)transportControlsView:(id)arg1 longPressBeginOnControlType:(int)arg2 ;
-(void)transportControlsView:(id)arg1 longPressEndOnControlType:(int)arg2 ;
-(void)transportControlsView:(id)arg1 tapOnAccessoryButtonType:(int)arg2 ;
@end

@protocol MPURemoteViewControllerPresentation
@required
-(void)remoteViewControllerDidFinish;
-(void)remoteViewControllerDidFinish;
@end

@protocol MPUChronologicalProgressViewDelegate
@optional
-(void)progressViewDidBeginScrubbing:(id)arg1 ;
-(void)progressViewDidEndScrubbing:(id)arg1 ;
-(void)progressView:(id)arg1 didScrubToCurrentTime:(double)arg2 ;
@end

@protocol MPUMediaControlsTitlesViewDelegate
@required
-(void)mediaControlsTitlesViewWasTapped:(id)arg1 ;
-(void)mediaControlsTitlesViewWasTapped:(id)arg1 ;
@end

@protocol MPAudioDeviceControllerDelegate
@optional
-(void)audioDeviceControllerAudioRoutesChanged:(id)arg1 ;
-(void)audioDeviceControllerMediaServerDied:(id)arg1 ;
@end

@protocol RUTrackActionsDelegate
@optional
-(void)trackActioningObject:(id)arg1 didSelectAction:(int)arg2 atIndex:(int)arg3 ;
-(void)trackActioningObjectDidChangeContentSize:(id)arg1 ;
@end

@protocol UIModalItemDelegate
@optional
-(void)willPresentModalItem:(id)arg1 ;
-(void)didPresentModalItem:(id)arg1 ;
-(BOOL)modalItem:(id)arg1 shouldDismissForButtonAtIndex:(int)arg2 ;
-(void)modalItem:(id)arg1 willDismissWithButtonIndex:(int)arg2 ;
-(void)modalItem:(id)arg1 didDismissWithButtonIndex:(int)arg2 ;
-(BOOL)modalItemShouldEnableFirstOtherButton:(id)arg1 ;
@end

@protocol UIPopoverControllerDelegate
@optional
-(BOOL)popoverControllerShouldDismissPopover:(id)arg1 ;
-(void)popoverControllerDidDismissPopover:(id)arg1 ;
//-(void)popoverController:(id)arg1 willRepositionPopoverToRect:(N)arg2 inView:(*)arg3 ;
@end
